### ISSUE TITLE
End date parameter

### ISSUE THREAD

**Issue by enricostano** [CollectivaT-dev/TimeOverflow#8]
Right now in the [Dockerfile](https://github.com/CollectivaT-dev/TimeOverflow/blob/master/Dockerfile#L23) we're fixing the `end_date` parameter to `2020-01-01`.

Should we change this @agfab @gullabi ?

**Comment by agfab** [comment]
Yes, that's the parameter which should be updated at each new execution of the code in order to get the updated values of the indicators. 
When we were developing the code we only had data available till 10th of January 2020, so we fixed it to 2020-01-01. 
Anyway, to get the most updated values you should set it to the current date, or to the first day of the current month or week. 
In my opinion, a monthly re-evaluation of the indicators is reasonable and meaningful. 
(Actually, now we could even run the code 8 times setting each time the _end_date_ parameter to the first day of the months between January 2020 and August 2020 and we would get 8 pictures of the metrics, gaining a first look at their temporal evolution.)

**Comment by enricostano** [comment]
I guess this is solved by now. Thanks!
